### ISSUE TITLE
Filter out inactve Devices

### ISSUE THREAD

**Issue by kgottschalk** [sebthebert/WWW-PushBullet#13]
The PushBullet API returns in the list of devices also inactive (deleted) devices. For these the device field {active} is false. Using the pushbullet tool to send messages to all devices (without specifiying one) then messages will be pushed also to inactive devices. I suggest that WWW::PushBullet filters out inactive devices.

**Comment by sebthebert** [comment]
Ok, I will work on that this week-end.

**Comment by kgottschalk** [comment]
Hallo Sebastien,

 

ist Deutsch ok?

 

Danke für das Script. Finde ich toll!

Ich habe den Filter bei mir eingebaut. Ich kann Dir geben was ich habe.

Hast Du eine Idee, warum ich Messages, die mit Deinem Script verschickt werden, auf meinem Handy doppelt bekomme. Auf meinem Laptop ist das nicht so.

 

Viele Grüße

Klaus

 

 

 

 

Klaus Gottschalk

0711-7286943

klaus.gottschalk@kgem.de

 

Von: Sebastien Thebert [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. November 2017 00:17
An: sebthebert/WWW-PushBullet <WWW-PushBullet@noreply.github.com>
Cc: kgottschalk <klaus@kgem.de>; Author <author@noreply.github.com>
Betreff: Re: [sebthebert/WWW-PushBullet] Filter out inactve Devices (#13)

 

Ok, I will work on that this week-end.

**Comment by sebthebert** [comment]
* inactive devices filtered out https://github.com/sebthebert/WWW-PushBullet/commit/1283a9d33b3b1063b750c0ec90e32e2d85d3a784
