### ISSUE TITLE
Add 'send sms' feature

### ISSUE THREAD

**Issue by sebthebert** [sebthebert/WWW-PushBullet#7]
https://docs.pushbullet.com/#send-sms

**Comment by xtetsuji** [comment]
@sebthebert That is insteresting. I will soon write this support, or I wait for this pull-request.

**Comment by sebthebert** [comment]
@xtetsuji I have already work on it this week-end, but it needs some code refactoring and new default options...

New release with this feature probably before friday !

**Comment by xtetsuji** [comment]
@sebthebert OK. I look forward to pull-request!

**Comment by sebthebert** [comment]
I'm late and didn't finish it completely, 
but you've got a working 'SMS sending feature in the [last commit](https://github.com/sebthebert/WWW-PushBullet/commit/b288ba055d761150b3c8a2e321eba3bc39b6dce5).

**Comment by realflash** [comment]
Hi Seb. What needs doing to release this feature? I'd be happy to contribute a PR to get it out there. I'd really like to use it without having to manually build the module.

**Comment by sebthebert** [comment]
[WWW::PushBullet v1.6.0](https://github.com/sebthebert/WWW-PushBullet/releases/tag/v1.6.0) is finaly here !
